#!/bin/sh

RESP=$(/usr/local/bin/voyager init --config /usr/local/etc/infinity-voyager/voyager.yaml 2>&1)
case "$RESP" in
    Error*)
        echo "
Enabled clef-signer but clef is not running.
Check https://docs.ethinfinity.org/ for more info.
After you fix configuration run 'voyager-get-addr' again.
        "
        ;;
    *)
        ETH_ADDRESS=$(echo "$RESP" | grep ethereum | cut -d' ' -f6 | tr -d '"')
        echo "
Please make sure there is sufficient eth and ifi available on $ETH_ADDRESS address.
You can get both Goerli ETH and Goerli IFI now via the ifiaar at https://ifi.ethinfinity.org/?transaction=buy&amount=10&slippage=30&receiver=0x$ETH_ADDRESS

After you get the funds start service with 'brew services start infinity-voyager'.
        "
        ;;
esac
