api-addr: :1633
bootnode: "/ip4/54.252.195.103/tcp/1634/p2p/4c3948a814c430d3be4768e96a6c461f9223c0a0c47ac531df2c3e117639e28b3dc07ebfa36f5c2e718520e3b23561ba3cdf4de5f51b925eb9f139b4c80b1656"
bootnode-mode: true
clef-signer-enable: false
clef-signer-endpoint: ""
clef-signer-ethereum-address: ""
config: ""
cors-allowed-origins: ["*"]
data-dir: C:/voyagerdata
db-block-cache-capacity: "33554432"
db-capacity: "5000000"
db-disable-seeks-compaction: false
db-open-files-limit: "200"
db-write-buffer-size: "33554432"
debug-api-addr: :1635
debug-api-enable: true
gateway-mode: true
global-pinning-enable: true
help: false
nat-addr: "54.252.195.103:1634"
network-id: "18888"
p2p-addr: :1634
p2p-quic-enable: true
p2p-ws-enable: true
password: "123456"
password-file: ""
payment-early: "1000000000000"
payment-threshold: "10000000000000"
payment-tolerance: "50000000000000"
resolver-options: []
standalone: false
swap-enable: true
swap-endpoint: http://54.252.195.103:8545
swap-factory-address: "0x5E2d32911A97382D7f7f1aC5f4Dd771bECD4D218"
swap-initial-deposit: "0"
tracing-enable: false
tracing-endpoint: 127.0.0.1:6831
tracing-service-name: fish
verbosity: info
welcome-message: ""